### PR TITLE
#5 - constant naming: NEWLINE -> NewLine

### PR DESCRIPTION
**Pull request by RPCMoritz**
This still breaks with the codacy regExp (I think), but it's consistent with the Scala style guide http://docs.scala-lang.org/style/naming-conventions.html

### CODE REVIEW

**Comment by FRosner** [comment]
Yeah I was wondering the same thing - because in Scala there are no real constants... Everything is final and if it is inside an object it's somewhat static.

Why is the build failing?

**Comment by RPCMoritz** [comment]
Build fails, because I missed another file importing the same constant. Fix in progress...

**Comment by FRosner** [comment]
@RPCMoritz will rebase soon and merge it. Sorry for the delay.

**Comment by FRosner** [comment]
image

@RPCMoritz breaking world record in number of commits, branches and merge commits for renaming a variable.

**Comment by FRosner** [comment]
Sorry man, I was not able to rebase and squash this within 5 minutes. I just renamed it myself again... :D

**Comment by RPCMoritz** [comment]
But did you also add a rule for codacy?

**Comment by FRosner** [comment]
I couldn't because the review was not completed. I don't know if I can add a rule. Do you know how it works? Otherwise we can just hit "ignore". But I will give them feedback on it.

Thanks!

**Pull request closed without merging**
